{
  "hash": "f495db08b88b8331c6ac15c55b2dc247",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Shubhanga Satyal\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(RColorBrewer)\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(knitr)\n# Load spatial data\n\n#| message: false\n#| results: hide\npa_counties <- st_read(\"data/Pennsylvania_County_Boundaries.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `/Users/shubhangasatyal/Desktop/GitHub/SS_PPA_REPO/labs/lab2/data/Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(\"data/hospitals.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `/Users/shubhangasatyal/Desktop/GitHub/SS_PPA_REPO/labs/lab2/data/hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\ncensus_tracts <- suppressMessages(tracts(state = \"PA\", cb = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |                                                                      |   1%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |=======                                                               |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |=======                                                               |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |===========                                                           |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |=================                                                     |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |===================                                                   |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |============================                                          |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |================================                                      |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |==================================                                    |  48%\n  |                                                                            \n  |===================================                                   |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |====================================                                  |  51%\n  |                                                                            \n  |=====================================                                 |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |=======================================                               |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |=========================================                             |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |===========================================                           |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |=============================================                         |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |===============================================                       |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |==================================================                    |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |====================================================                  |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |======================================================                |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |========================================================              |  81%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |==========================================================            |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |============================================================          |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |==============================================================        |  88%\n  |                                                                            \n  |===============================================================       |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |=================================================================     |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |===================================================================   |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |===================================================================== |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\ncensus_tracts <- st_transform(census_tracts, st_crs(pa_counties))\n\n# Check that all data loaded correctly\nhead(pa_counties)%>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| OBJECTID| MSLINK|COUNTY_NAM |COUNTY_NUM |FIPS_COUNT |COUNTY_ARE |COUNTY_PER | NUMERIC_LA| COUNTY_N_1| AREA_SQ_MI|SOUND |SPREAD_SHE |IMAGE_NAME |NOTE_FILE |VIDEO |DISTRICT_N |PA_CTY_COD |MAINT_CTY_ |DISTRICT_O |geometry                       |\n|--------:|------:|:----------|:----------|:----------|:----------|:----------|----------:|----------:|----------:|:-----|:----------|:----------|:---------|:-----|:----------|:----------|:----------|:----------|:------------------------------|\n|      336|     46|MONTGOMERY |46         |091        |NA         |NA         |          5|         46|   487.4271|NA    |NA         |poll.bmp   |NA        |NA    |06         |46         |4          |6-4        |MULTIPOLYGON (((-8398884 48... |\n|      337|      8|BRADFORD   |08         |015        |NA         |NA         |          2|          8|  1161.3379|NA    |NA         |poll.bmp   |NA        |NA    |03         |08         |9          |3-9        |MULTIPOLYGON (((-8558633 51... |\n|      338|      9|BUCKS      |09         |017        |NA         |NA         |          5|          9|   622.0836|NA    |NA         |poll.bmp   |NA        |NA    |06         |09         |1          |6-1        |MULTIPOLYGON (((-8367360 49... |\n|      339|     58|TIOGA      |58         |117        |NA         |NA         |          2|         58|  1137.2480|NA    |NA         |poll.bmp   |NA        |NA    |03         |59         |7          |3-7        |MULTIPOLYGON (((-8558633 51... |\n|      340|     59|UNION      |59         |119        |NA         |NA         |          2|         59|   319.1893|NA    |NA         |poll.bmp   |NA        |NA    |03         |60         |8          |3-8        |MULTIPOLYGON (((-8562865 49... |\n|      341|     60|VENANGO    |60         |121        |NA         |NA         |          3|         60|   683.3676|NA    |NA         |poll.bmp   |NA        |NA    |01         |61         |5          |1-5        |MULTIPOLYGON (((-8870781 50... |\n\n\n:::\n\n```{.r .cell-code}\nhead(hospitals)%>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|CHIEF_EXEC                |CHIEF_EX_1              |FACILITY_U                     | LONGITUDE|COUNTY       |FACILITY_N                              |STREET                         |CITY_OR_BO   | LATITUDE|TELEPHONE_   |ZIP_CODE |geometry                 |\n|:-------------------------|:-----------------------|:------------------------------|---------:|:------------|:---------------------------------------|:------------------------------|:------------|--------:|:------------|:--------|:------------------------|\n|Peter J Adamo             |President               |https://www.phhealthcare.org   | -79.91131|Washington   |Penn Highlands Mon Valley               |1163 Country Club Road         |Monongahela  | 40.18193|724-258-1000 |15063    |POINT (-8895686 4892415) |\n|Autumn DeShields          |Chief Executive Officer |https://www.malvernbh.com      | -75.17005|Philadelphia |MALVERN BEHAVIORAL HEALTH               |1930 South Broad Street Unit 4 |Philadelphia | 39.92619|610-480-8919 |19145    |POINT (-8367892 4855223) |\n|Shawn Parekh              |Chief Executive Officer |https://roxboroughmemorial.com | -75.20963|Philadelphia |Roxborough Memorial Hospital            |5800 Ridge Avenue              |Philadelphia | 40.02869|215-483-9900 |19128    |POINT (-8372298 4870112) |\n|DIANE HRITZ               |Chief Executive Officer |https://www.ashospital.net     | -80.27907|Washington   |ADVANCED SURGICAL HOSPITAL              |100 TRICH DRIVE\nSUITE 1         |WASHINGTON   | 40.15655|7248840710   |15301    |POINT (-8936626 4888717) |\n|Tim Harclerode            |Chief Executive Officer |https://www.conemaugh.org      | -79.02513|Somerset     |DLP Conemaugh Meyersdale Medical Center |200 Hospital Drive             |Meyersdale   | 39.80913|814-634-5911 |15552    |POINT (-8797037 4838244) |\n|Richard McLaughlin MD MBA |Chief Executive Officer |https://towerhealth.org        | -75.61213|Montgomery   |Pottstown Hospital, LLC                 |1600 East High Street          |Pottstown    | 40.24273|6103277000   |19464    |POINT (-8417104 4901278) |\n\n\n:::\n\n```{.r .cell-code}\nhead(census_tracts)%>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|STATEFP |COUNTYFP |TRACTCE |GEOIDFQ              |GEOID       |NAME   |NAMELSAD            |STUSPS |NAMELSADCO   |STATE_NAME   |LSAD |   ALAND| AWATER|geometry                       |\n|:-------|:--------|:-------|:--------------------|:-----------|:------|:-------------------|:------|:------------|:------------|:----|-------:|------:|:------------------------------|\n|42      |001      |031101  |1400000US42001031101 |42001031101 |311.01 |Census Tract 311.01 |PA     |Adams County |Pennsylvania |CT   | 3043185|      0|MULTIPOLYGON (((-8575060 48... |\n|42      |013      |100400  |1400000US42013100400 |42013100400 |1004   |Census Tract 1004   |PA     |Blair County |Pennsylvania |CT   |  993724|      0|MULTIPOLYGON (((-8730207 49... |\n|42      |013      |100500  |1400000US42013100500 |42013100500 |1005   |Census Tract 1005   |PA     |Blair County |Pennsylvania |CT   | 1130204|      0|MULTIPOLYGON (((-8729297 49... |\n|42      |013      |100800  |1400000US42013100800 |42013100800 |1008   |Census Tract 1008   |PA     |Blair County |Pennsylvania |CT   |  996553|      0|MULTIPOLYGON (((-8728636 49... |\n|42      |013      |101900  |1400000US42013101900 |42013101900 |1019   |Census Tract 1019   |PA     |Blair County |Pennsylvania |CT   |  573726|      0|MULTIPOLYGON (((-8728378 49... |\n|42      |011      |011200  |1400000US42011011200 |42011011200 |112    |Census Tract 112    |PA     |Berks County |Pennsylvania |CT   | 1539365|   9308|MULTIPOLYGON (((-8455198 49... |\n\n\n:::\n\n```{.r .cell-code}\nhead(census_tracts)%>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|STATEFP |COUNTYFP |TRACTCE |GEOIDFQ              |GEOID       |NAME   |NAMELSAD            |STUSPS |NAMELSADCO   |STATE_NAME   |LSAD |   ALAND| AWATER|geometry                       |\n|:-------|:--------|:-------|:--------------------|:-----------|:------|:-------------------|:------|:------------|:------------|:----|-------:|------:|:------------------------------|\n|42      |001      |031101  |1400000US42001031101 |42001031101 |311.01 |Census Tract 311.01 |PA     |Adams County |Pennsylvania |CT   | 3043185|      0|MULTIPOLYGON (((-8575060 48... |\n|42      |013      |100400  |1400000US42013100400 |42013100400 |1004   |Census Tract 1004   |PA     |Blair County |Pennsylvania |CT   |  993724|      0|MULTIPOLYGON (((-8730207 49... |\n|42      |013      |100500  |1400000US42013100500 |42013100500 |1005   |Census Tract 1005   |PA     |Blair County |Pennsylvania |CT   | 1130204|      0|MULTIPOLYGON (((-8729297 49... |\n|42      |013      |100800  |1400000US42013100800 |42013100800 |1008   |Census Tract 1008   |PA     |Blair County |Pennsylvania |CT   |  996553|      0|MULTIPOLYGON (((-8728636 49... |\n|42      |013      |101900  |1400000US42013101900 |42013101900 |1019   |Census Tract 1019   |PA     |Blair County |Pennsylvania |CT   |  573726|      0|MULTIPOLYGON (((-8728378 49... |\n|42      |011      |011200  |1400000US42011011200 |42011011200 |112    |Census Tract 112    |PA     |Berks County |Pennsylvania |CT   | 1539365|   9308|MULTIPOLYGON (((-8455198 49... |\n\n\n:::\n\n```{.r .cell-code}\nsummarise(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 0 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n                        geometry\n1 POLYGON ((-8907167 4825507,...\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**. \n\n\n\n- **How many hospitals are in your dataset?**. \n\n  223  \n- **How many census tracts?**. \n  \n  3,345  \n- **What coordinate reference system is each dataset in?**.   \n  \n  \n  All use WGS 84 after I transformed the coordinate system. \n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\ndemographic_data <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  variables = c(\n    total_population = \"B01003_001\",\n    median_income = \"B19013_001\",\n    a = \"B01001_020\",\n    b = \"B01001_021\",\n    c = \"B01001_022\",\n    d = \"B01001_023\",\n    e = \"B01001_024\",\n    f = \"B01001_025\",\n    g = \"B01001_044\",\n    h = \"B01001_045\",\n    i = \"B01001_046\",\n    j = \"B01001_047\",\n    k = \"B01001_048\",\n    l = \"B01001_049\"\n  ),\n  year = 2022,\n  survey = \"acs5\",\n  output = \"wide\"\n) %>%\n  mutate(\n    pop_65plusE =\n      aE + bE + cE + dE + eE + fE +\n      gE + hE + iE + jE + kE + lE\n      ) %>%\n  mutate(\n    NAME = NAME %>%\n      str_remove(\"Census Tract \") %>%\n      str_remove(\"; Pennsylvania\")\n  )%>%\n  select(\n    GEOID,\n    `County Name` = NAME,\n    `Total Population` = total_populationE,\n    `Total Population 65 Y+` = pop_65plusE,\n    `Median HH Income` = median_incomeE\n  )\n\nhead(demographic_data)%>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|GEOID       |County Name          | Total Population| Total Population 65 Y+| Median HH Income|\n|:-----------|:--------------------|----------------:|----------------------:|----------------:|\n|42001030101 |301.01; Adams County |             2658|                    521|            80231|\n|42001030103 |301.03; Adams County |             2416|                    467|           111603|\n|42001030104 |301.04; Adams County |             3395|                    730|            81150|\n|42001030200 |302; Adams County    |             5475|                   1020|            68363|\n|42001030300 |303; Adams County    |             4412|                    722|            81577|\n|42001030400 |304; Adams County    |             5462|                   1206|            88558|\n\n\n:::\n\n```{.r .cell-code}\n# Join to tract boundaries\njoin_tract_boundaries <- census_tracts %>%\n  left_join(demographic_data, by = \"GEOID\")\n\nhead(join_tract_boundaries) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|STATEFP |COUNTYFP |TRACTCE |GEOIDFQ              |GEOID       |NAME   |NAMELSAD            |STUSPS |NAMELSADCO   |STATE_NAME   |LSAD |   ALAND| AWATER|County Name          | Total Population| Total Population 65 Y+| Median HH Income|geometry                       |\n|:-------|:--------|:-------|:--------------------|:-----------|:------|:-------------------|:------|:------------|:------------|:----|-------:|------:|:--------------------|----------------:|----------------------:|----------------:|:------------------------------|\n|42      |001      |031101  |1400000US42001031101 |42001031101 |311.01 |Census Tract 311.01 |PA     |Adams County |Pennsylvania |CT   | 3043185|      0|311.01; Adams County |             5070|                    946|            61847|MULTIPOLYGON (((-8575060 48... |\n|42      |013      |100400  |1400000US42013100400 |42013100400 |1004   |Census Tract 1004   |PA     |Blair County |Pennsylvania |CT   |  993724|      0|1004; Blair County   |             1589|                    238|            67120|MULTIPOLYGON (((-8730207 49... |\n|42      |013      |100500  |1400000US42013100500 |42013100500 |1005   |Census Tract 1005   |PA     |Blair County |Pennsylvania |CT   | 1130204|      0|1005; Blair County   |             3380|                    463|            50450|MULTIPOLYGON (((-8729297 49... |\n|42      |013      |100800  |1400000US42013100800 |42013100800 |1008   |Census Tract 1008   |PA     |Blair County |Pennsylvania |CT   |  996553|      0|1008; Blair County   |             1860|                    282|            64583|MULTIPOLYGON (((-8728636 49... |\n|42      |013      |101900  |1400000US42013101900 |42013101900 |1019   |Census Tract 1019   |PA     |Blair County |Pennsylvania |CT   |  573726|      0|1019; Blair County   |             1436|                    636|            16429|MULTIPOLYGON (((-8728378 49... |\n|42      |011      |011200  |1400000US42011011200 |42011011200 |112    |Census Tract 112    |PA     |Berks County |Pennsylvania |CT   | 1539365|   9308|112; Berks County    |             4533|                    600|            56818|MULTIPOLYGON (((-8455198 49... |\n\n\n:::\n\n```{.r .cell-code}\njoin_tract_boundaries%>%\n  select(`Median HH Income`)%>%\n  summary()%>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|   |Median HH Income |         geometry  |\n|:--|:----------------|:------------------|\n|   |Min.   : 11558   |MULTIPOLYGON :3445 |\n|   |1st Qu.: 55924   |epsg:3857    :   0 |\n|   |Median : 70188   |+proj=merc...:   0 |\n|   |Mean   : 77527   |NA                 |\n|   |3rd Qu.: 93286   |NA                 |\n|   |Max.   :250001   |NA                 |\n|   |NA's   :62       |NA                 |\n\n\n:::\n:::\n\n\n**Questions to answer:**. \n\n\n\n\n\n\n- **What year of ACS data are you using?**.  \n  \n  \n  2022.\n\n- **How many tracts have missing income data?**. \n\n\n  2023.\n\n- **What is the median income across all PA census tracts?**. \n\n\n  70,188.\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\n\nidentify_vulnerability <- join_tract_boundaries %>%\n  mutate(\n    plus_pct = (`Total Population 65 Y+` / `Total Population`) * 100,\n    category = case_when(\n      `Median HH Income` < 55924 & plus_pct > 20 ~ \"Vulnerable\",\n      TRUE ~ \"Not Vulnerable\"\n    )\n  )\n\ncount(identify_vulnerability, category)%>%\n  mutate(\n    percentage_vulner = (n / sum(n))*100\n  )%>%\n  select(category, n, percentage_vulner)%>%\n  kable(digit = 1)\n```\n\n::: {.cell-output-display}\n\n\n|category       |    n| percentage_vulner|geometry                       |\n|:--------------|----:|-----------------:|:------------------------------|\n|Not Vulnerable | 3172|              92.1|MULTIPOLYGON (((-8914014 48... |\n|Vulnerable     |  273|               7.9|MULTIPOLYGON (((-8895128 48... |\n\n\n:::\n\n```{.r .cell-code}\nhead(identify_vulnerability)%>%\n  kable(digit = 1)\n```\n\n::: {.cell-output-display}\n\n\n|STATEFP |COUNTYFP |TRACTCE |GEOIDFQ              |GEOID       |NAME   |NAMELSAD            |STUSPS |NAMELSADCO   |STATE_NAME   |LSAD |   ALAND| AWATER|County Name          | Total Population| Total Population 65 Y+| Median HH Income|geometry                       | plus_pct|category       |\n|:-------|:--------|:-------|:--------------------|:-----------|:------|:-------------------|:------|:------------|:------------|:----|-------:|------:|:--------------------|----------------:|----------------------:|----------------:|:------------------------------|--------:|:--------------|\n|42      |001      |031101  |1400000US42001031101 |42001031101 |311.01 |Census Tract 311.01 |PA     |Adams County |Pennsylvania |CT   | 3043185|      0|311.01; Adams County |             5070|                    946|            61847|MULTIPOLYGON (((-8575060 48... |     18.7|Not Vulnerable |\n|42      |013      |100400  |1400000US42013100400 |42013100400 |1004   |Census Tract 1004   |PA     |Blair County |Pennsylvania |CT   |  993724|      0|1004; Blair County   |             1589|                    238|            67120|MULTIPOLYGON (((-8730207 49... |     15.0|Not Vulnerable |\n|42      |013      |100500  |1400000US42013100500 |42013100500 |1005   |Census Tract 1005   |PA     |Blair County |Pennsylvania |CT   | 1130204|      0|1005; Blair County   |             3380|                    463|            50450|MULTIPOLYGON (((-8729297 49... |     13.7|Not Vulnerable |\n|42      |013      |100800  |1400000US42013100800 |42013100800 |1008   |Census Tract 1008   |PA     |Blair County |Pennsylvania |CT   |  996553|      0|1008; Blair County   |             1860|                    282|            64583|MULTIPOLYGON (((-8728636 49... |     15.2|Not Vulnerable |\n|42      |013      |101900  |1400000US42013101900 |42013101900 |1019   |Census Tract 1019   |PA     |Blair County |Pennsylvania |CT   |  573726|      0|1019; Blair County   |             1436|                    636|            16429|MULTIPOLYGON (((-8728378 49... |     44.3|Vulnerable     |\n|42      |011      |011200  |1400000US42011011200 |42011011200 |112    |Census Tract 112    |PA     |Berks County |Pennsylvania |CT   | 1539365|   9308|112; Berks County    |             4533|                    600|            56818|MULTIPOLYGON (((-8455198 49... |     13.2|Not Vulnerable |\n\n\n:::\n:::\n\n\n**Questions to answer:**. \n\n\n- **What income threshold did you choose and why?**. \n \n \n  less than 55,943 (Lower Quartile)\n  \n- **What elderly population threshold did you choose and why?**. \n\n\n  I chose elderly population over 65 year old, and in areas where the population is more than 20%. \n\n- **How many tracts meet your vulnerability criteria?**. \n  \n  \n  273. \n  \n- **What percentage of PA census tracts are considered vulnerable by your definition?**. \n\n  \n  7.9%. \n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\nhos <- st_transform(hospitals, 3365)\nvul <- st_transform(identify_vulnerability, 3365)\n\n# Calculate distance from each tract centroid to nearest hospital\nvul_new <- vul %>%\n  filter(category == \"Vulnerable\") %>% \n  mutate(\n    dist_near_hos = as.numeric(st_distance(\n      st_centroid(.), st_union(hos)\n    )) / 1609.34\n    )\nhead(vul_new)%>%\n  kable(digit=1)\n```\n\n::: {.cell-output-display}\n\n\n|STATEFP |COUNTYFP |TRACTCE |GEOIDFQ              |GEOID       |NAME |NAMELSAD          |STUSPS |NAMELSADCO            |STATE_NAME   |LSAD |   ALAND| AWATER|County Name                | Total Population| Total Population 65 Y+| Median HH Income|geometry                       | plus_pct|category   | dist_near_hos|\n|:-------|:--------|:-------|:--------------------|:-----------|:----|:-----------------|:------|:---------------------|:------------|:----|-------:|------:|:--------------------------|----------------:|----------------------:|----------------:|:------------------------------|--------:|:----------|-------------:|\n|42      |013      |101900  |1400000US42013101900 |42013101900 |1019 |Census Tract 1019 |PA     |Blair County          |Pennsylvania |CT   |  573726|      0|1019; Blair County         |             1436|                    636|            16429|MULTIPOLYGON (((1785456 431... |     44.3|Vulnerable |           1.4|\n|42      |021      |013000  |1400000US42021013000 |42021013000 |130  |Census Tract 130  |PA     |Cambria County        |Pennsylvania |CT   | 1517381|      0|130; Cambria County        |             2658|                    562|            47825|MULTIPOLYGON (((1708617 385... |     21.1|Vulnerable |          43.2|\n|42      |065      |950100  |1400000US42065950100 |42065950100 |9501 |Census Tract 9501 |PA     |Jefferson County      |Pennsylvania |CT   | 3068556|  82544|9501; Jefferson County     |             2192|                    531|            47404|MULTIPOLYGON (((1678066 700... |     24.2|Vulnerable |          30.1|\n|42      |071      |011300  |1400000US42071011300 |42071011300 |113  |Census Tract 113  |PA     |Lancaster County      |Pennsylvania |CT   | 2637735|    772|113; Lancaster County      |             4387|                   1135|            55346|MULTIPOLYGON (((2315459 259... |     25.9|Vulnerable |          21.6|\n|42      |079      |217700  |1400000US42079217700 |42079217700 |2177 |Census Tract 2177 |PA     |Luzerne County        |Pennsylvania |CT   | 1452436|      0|2177; Luzerne County       |             5258|                   1120|            46199|MULTIPOLYGON (((2454551 601... |     21.3|Vulnerable |           5.1|\n|42      |097      |082100  |1400000US42097082100 |42097082100 |821  |Census Tract 821  |PA     |Northumberland County |Pennsylvania |CT   |  820185|      0|821; Northumberland County |             2350|                    599|            31944|MULTIPOLYGON (((2230884 555... |     25.5|Vulnerable |          31.2|\n\n\n:::\n\n```{.r .cell-code}\nnew_summary <- vul_new %>%\n  select(dist_near_hos)%>%\n  summary()\n\nnew_summary%>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|   |dist_near_hos    |         geometry |\n|:--|:----------------|:-----------------|\n|   |Min.   : 0.06874 |MULTIPOLYGON :273 |\n|   |1st Qu.: 3.97367 |epsg:3365    :  0 |\n|   |Median : 8.29352 |+proj=lcc ...:  0 |\n|   |Mean   :14.89639 |NA                |\n|   |3rd Qu.:19.88491 |NA                |\n|   |Max.   :84.06255 |NA                |\n\n\n:::\n\n```{.r .cell-code}\ndist_15 <- vul_new%>%\n  filter(dist_near_hos > 15 )%>%\n  count()%>%\n  select(n) %>%\n  st_drop_geometry(.)\ndist_15%>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|  n|\n|--:|\n| 85|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\nI chose my projection as 3365 because it is the apt projection for Pennsylvania South for distance calculations. \n\n**Questions to answer:**. \n\n  \n  \n   What is the average distance to the nearest hospital for vulnerable tracts?  14.88 Miles\n\n\n**What is the maximum distance?** \n   \n   84.06 Miles\n\n\n\n**How many vulnerable tracts are more than 15 miles from the nearest hospital?**. \n  \n  \n  85\n  \n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\n\nunderserved <- vul_new %>%\n  mutate(\n    serv_under_or = case_when(\n      dist_near_hos > 15 ~ \"underserved\",\n      TRUE ~ \"vulnerable but served\"\n    )\n  )\n\nnew1_summary <- underserved %>%\n  count(serv_under_or)%>%\n  mutate (\n    underserv_pct = (n/sum(n)*100)\n  )\n\nglimpse(new1_summary)%>%\n  kable(digit = 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2\nColumns: 4\n$ serv_under_or <chr> \"underserved\", \"vulnerable but served\"\n$ n             <int> 85, 188\n$ geometry      <MULTIPOLYGON [US_survey_foot]> MULTIPOLYGON (((1506307 154..., MULTIPOLYGON (((1365750 …\n$ underserv_pct <dbl> 31.13553, 68.86447\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|serv_under_or         |   n|geometry                       | underserv_pct|\n|:---------------------|---:|:------------------------------|-------------:|\n|underserved           |  85|MULTIPOLYGON (((1506307 154... |          31.1|\n|vulnerable but served | 188|MULTIPOLYGON (((1365750 303... |          68.9|\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- **How many tracts are underserved?**\n\n  85 are underserved\n\n\n- **What percentage of vulnerable tracts are underserved?**. \n\n  31.1% are underserved\n  \n- **Does this surprise you? Why or why not?**. \n\n  I do not have any context for \"surprise\" here, however I am conerned that     31% areas are underserved. Therefore more intervention and planning is        required. \n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\n\n\npcounty <- st_transform(pa_counties, 3365)\npcensustract <- st_transform(census_tracts, 3365)\n\nnew_spatial_join <- underserved %>%\n  st_join(pcounty) %>%\n  group_by(COUNTY_NAM) %>%\n  summarise(\n    total_vulnerable = n(),\n    total_underserved = sum(serv_under_or == \"underserved\"),\n    pct_underserved = (total_underserved / total_vulnerable) * 100,\n    avg_dist = mean(dist_near_hos),\n    total_vul_pop = sum(`Total Population`)\n  )\n\n st_transform(new_spatial_join, 3365)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 59 features and 6 fields\nGeometry type: GEOMETRY\nDimension:     XY\nBounding box:  xmin: 1204220 ymin: 142405.5 xmax: 2736008 ymax: 1028009\nProjected CRS: NAD83(HARN) / Pennsylvania South (ftUS)\n# A tibble: 59 × 7\n   COUNTY_NAM total_vulnerable total_underserved pct_underserved avg_dist\n * <chr>                 <int>             <int>           <dbl>    <dbl>\n 1 ALLEGHENY                47                 2            4.26     8.03\n 2 ARMSTRONG                 5                 3           60       27.5 \n 3 BEAVER                    8                 1           12.5      9.15\n 4 BEDFORD                   5                 4           80       29.8 \n 5 BERKS                     2                 2          100       19.1 \n 6 BLAIR                     3                 1           33.3     10.1 \n 7 BRADFORD                  3                 2           66.7     31.5 \n 8 CAMBRIA                  14                 7           50       20.8 \n 9 CAMERON                   4                 4          100       48.8 \n10 CARBON                    2                 1           50       16.7 \n# ℹ 49 more rows\n# ℹ 2 more variables: total_vul_pop <dbl>,\n#   geometry <MULTIPOLYGON [US_survey_foot]>\n```\n\n\n:::\n\n```{.r .cell-code}\n# Aggregate statistics by county\npct_uns <- new_spatial_join %>% \n  arrange(desc(pct_underserved))%>%\n  head(5) %>%\n  kable(digits = 1)\n\nnew_spatial_join%>%\n  arrange(desc(avg_dist))%>%\n  head(5)%>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|COUNTY_NAM | total_vulnerable| total_underserved| pct_underserved| avg_dist| total_vul_pop|geometry                       |\n|:----------|----------------:|-----------------:|---------------:|--------:|-------------:|:------------------------------|\n|PERRY      |                2|                 2|             100| 57.52312|          5800|MULTIPOLYGON (((1970270 384... |\n|COLUMBIA   |                1|                 1|             100| 55.47065|           918|MULTIPOLYGON (((2266086 764... |\n|CENTRE     |                3|                 3|             100| 49.45367|         11192|MULTIPOLYGON (((1793414 568... |\n|CAMERON    |                4|                 4|             100| 48.80753|          8919|MULTIPOLYGON (((1784634 645... |\n|FOREST     |                3|                 3|             100| 46.18697|          6029|POLYGON ((1485466 781508.1,... |\n\n\n:::\n\n```{.r .cell-code}\ncounty_map_data <- pcounty %>%\n  left_join(\n    st_drop_geometry(new_spatial_join), by = \"COUNTY_NAM\")\n\nggplot() +\n  geom_sf(data = county_map_data, aes(fill = pct_underserved), color = \"black\") +\n  scale_fill_viridis_c(name = \"% Underserved\", na.value = \"navy\", option = \"inferno\") +\n  labs(title = \"Underserved Vulnerable Populations by County\") +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template--1-_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts. \n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**. \n\n\n- **Which 5 counties have the highest percentage of underserved vulnerable tracts?**. \n  \n  Berks, Cameron, Centre, Clarion, Clinton\n\n- **Which counties have the most vulnerable people living far from hospitals?**. \n  \n  Perry, Columbia, Centre, Cameron, Forest\n\n- **Are there any patterns in where underserved counties are located?**. \n  \n  \n  The vulnerable areas are further away from Philadelphia towards central PA, with more concentration in central northwest PA.\n  \n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\n\nnames(new_spatial_join)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"COUNTY_NAM\"        \"total_vulnerable\"  \"total_underserved\"\n[4] \"pct_underserved\"   \"avg_dist\"          \"total_vul_pop\"    \n[7] \"geometry\"         \n```\n\n\n:::\n\n```{.r .cell-code}\nhealth_care <- new_spatial_join %>%\n  st_drop_geometry() %>%\n  arrange(desc(pct_underserved), desc(avg_dist)) %>%\n  slice_head(n = 10) %>%\n  mutate(\n    total_vul_pop = comma(total_vul_pop)\n    )%>%\n  select(\n    `County Name` = COUNTY_NAM,\n    `Avg Distance from Nearest Hospital (miles)`= avg_dist,\n    `% Underserved Tracts among Vulnerable Tracts` = pct_underserved,\n    `Population in these Tracts` = total_vul_pop,\n    `Total Underserved Tracts` = total_underserved,\n    `Total Vulnerable Tracts` = total_vulnerable\n  )\n\nhealth_care%>%\n  kable(\n    digits = 0,\n    caption = \"Priority Table for Healthcare Investments\"\n        )\n```\n\n::: {.cell-output-display}\n\n\nTable: Priority Table for Healthcare Investments\n\n|County Name    | Avg Distance from Nearest Hospital (miles)| % Underserved Tracts among Vulnerable Tracts|Population in these Tracts | Total Underserved Tracts| Total Vulnerable Tracts|\n|:--------------|------------------------------------------:|--------------------------------------------:|:--------------------------|------------------------:|-----------------------:|\n|PERRY          |                                         58|                                          100|5,800                      |                        2|                       2|\n|COLUMBIA       |                                         55|                                          100|918                        |                        1|                       1|\n|CENTRE         |                                         49|                                          100|11,192                     |                        3|                       3|\n|CAMERON        |                                         49|                                          100|8,919                      |                        4|                       4|\n|FOREST         |                                         46|                                          100|6,029                      |                        3|                       3|\n|ELK            |                                         46|                                          100|12,550                     |                        5|                       5|\n|HUNTINGDON     |                                         44|                                          100|7,669                      |                        3|                       3|\n|SULLIVAN       |                                         44|                                          100|4,828                      |                        2|                       2|\n|MONROE         |                                         42|                                          100|7,428                      |                        3|                       3|\n|NORTHUMBERLAND |                                         41|                                          100|20,008                     |                        7|                       7|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\n\nggplot() +\n  geom_sf(data = county_map_data, aes(fill = pct_underserved), color = \"black\") +\n  geom_sf(data = hos, color = \"green\", size = 0.9, alpha = 0.9) +\n  scale_fill_viridis_c(name = \"% Underserved\",option = \"inferno\", na.value = \"navy\") +\n  labs(\n    title = \"Underserved Vulnerable Tracts\",\n    subtitle = \"% of vulnerable counties that are underserved\",\n    caption = \"Green points = Hospitals\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template--1-_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\n\nggplot() +\n  geom_sf(data = county_map_data, fill = \"white\", color = \"black\") +\n  geom_sf(data = underserved, aes(fill = serv_under_or), color = NA) +\n  geom_sf(data = hos, color = \"green\", size = 0.9, alpha = 0.9) +\n  scale_fill_viridis_d(name = \"Status\", option = \"plasma\") +\n  labs(\n    title = \"Underserved Vulnerable Tracts\",\n    subtitle = \"Tracts vulnerable and more than 15 miles from a hospital are underserved\",\n    caption = \"Green points = Hospitals\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template--1-_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n\nggplot(vul_new) +\n  aes(x = dist_near_hos) +\n  geom_histogram(bins = 25, fill = \"navy\", color = \"white\", alpha = 0.7) +\n   geom_vline(xintercept = 15, color = \"green\", linetype = \"dashed\") +\n  labs(\n    title = \"Distribution of Distances to Nearest Hospital\",\n    x = \"Distance to Nearest Hospital (miles)\",\n    y = \"Number of Vulnerable Tracts\",\n    subtitle = \"green line represents the 15 mile threshold for underserved\",\n    caption = \"most vulnerable census tracts have access to a hospital within 25 miles,\n    with high concentration of around 90 tracts with hospital within 5-10 miles\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_template--1-_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\n```\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\n- What is the data source and date?\n- How many features does it contain?\n- What CRS is it in? Did you need to transform it?\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n```\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\n[Write your findings here]\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n2. Submit the correct and working links of your assignment on Canvas\n\n---\n\n",
    "supporting": [
      "lab2_template--1-_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}